changelog:
  exclude:
    labels: [skip]
  categories:
    - { title: Documentation, labels: [docs] }
    - { title: Dependencies, labels: [deps] }
    - { title: Features, labels: [feature] }
    - { title: Tooling, labels: [tooling] }
    - { title: Bug fixes, labels: [bug] }
    - { title: Other, labels: ["*"] }
