[
  ../console/default.nix
  ../docker/default.nix
  ../minikube/default.nix
  ../go/default.nix
  ../nodejs/default.nix
  ../python/default.nix
  ../aws/default.nix
  ../gcloud/default.nix
  ../posting/default.nix
  ../harlequin/default.nix
  ./workspace.nix
]
