name: Labels flow

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, labeled, unlabeled]

concurrency:
  group: pr-labels-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  pull-requests: read

jobs:
  check-label:
    name: check label
    runs-on: ubuntu-24.04
    steps:
      - uses: mr-chelyshkin/actions/check-changelog-label@v1
